apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mayapp-replicaset
  labels:
    app: myapp
    location: Ukraine
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        location: Ukraine
    spec:
      containers:
        - name: nginx-container
          image: nginx
  replicas: 3
  selector: 
    matchLabels:
      location: Ukraine
